version: "3.7"

services:
  go-api:
    container_name: "go-api"
    build: 
      context: ./go-api
      dockerfile: Dockerfile
    ports: 
      - 8080:8080
    volumes: 
      - ./go-api:/usr/app
    depends_on: 
        - go-api-db
    env_file: 
        - ./go-api/config/.env
  go-api-db:
    image: mysql/mysql-server
    container_name: go-api-db
    environment: 
      MYSQL_USER: notSuperUser
      MYSQL_PASSWORD: 123456
      MYSQL_DATABASE: go-api
    volumes: 
      - go_api_volume:/var/lib/mysql
    ports: 
      - "3306:3306"

volumes: 
  go_api_volume:
    name: go_api_volume